sudo: required
services:
  - docker

before_install:
  - docker build -t akhilvs007/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run akhilvs007/react-test npm test -- --coverage

after_success:
  - docker build -t akhilvs007/multi-client ./client
  - docker build -t akhilvs007/multi-nginx ./nginx
  - docker build -t akhilvs007/multi-server ./server
  - docker build -t akhilvs007/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push akhilvs007/multi-client
  - docker push akhilvs007/multi-nginx
  - docker push akhilvs007/multi-server
  - docker push akhilvs007/multi-worker
  
deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-south-1-682476747761
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

